- hosts: localhost
  pre_tasks:
    - name: Update dnf repository
      dnf: update_cache=yes
      changed_when: false
  vars:
    user: "jhanna"
    dotfile_dir: "~/Documents/dotfiles"
    tools_dir: "/home/jhanna/Development/tools"
  tasks:
    - name: Setup universal roles
      include_tasks: setup-shared.yml

    - name: Setup mac specific roles
      include_tasks: setup-mac.yml
      when: ansible_os_family == 'Darwin'

    - name: Setup linux specific roles
      include_tasks: setup-linux.yml
      when: not ansible_os_family == 'Darwin'

    - name: Run post install roles
      include_tasks: post-install.yml
