- hosts: localhost
  become: true
  pre_tasks:
    - name: Update dnf repository
      dnf: update_cache=yes
      changed_when: False
  vars:
    user: "jhanna"
  roles:
    - trackpad
    - dotfiles
    - dev
    - utility
    - i3wm
    - urxvt
    - keyboard
    - zsh
    - vim
    - firefox
    - flathub
