- hosts: localhost
  pre_tasks:
    - name: Update dnf repository
      dnf: update_cache=yes
      changed_when: false
  vars:
    user: "jhanna"
    dotfile_dir: "~/Documents/dotfiles"
  roles:
    - trackpad
    - dotfiles
    - dev
    - utility
    - i3wm
    - urxvt
    - zsh
    - keyboard
    - vim
    - firefox
    - flathub
