# Install htop, xclip, dnf auto-update, redshift
---
- name: Install packages
  package: name={{ item }} state=present
  with_items:
    - htop
    - xclip
    - redshift

      # - name: Link redshift config

      # - name: Set dnf auto-updates on
