# Install htop, xclip, dnf auto-update, redshift
---
- name: Install packages
  package: name={{ item }} state=latest
  with_itms:
    - htop
    - xclip
    - redshift

- name: Link redshift config

- name: Set dnf auto-updates on
