# Clone the dotfiles, install stow, let subsequent roles link them
---
- name: Clone dotfile repo locally
  git:
    repo: "https://www.github.com/jeremy-hanna/dotfiles.git"
    dest: "~/Document/dotfiles"
    version: "fedora-environment"
    accept_hostkey: false
  become: false


  #- name: Check if dotfiles are stow links to this directory already

  #- name: Ensure dotfiles aren't dirty

  #- name: Install GNU Stow
