# Clone the dotfiles, install stow, let subsequent roles link them
---
- name: Install git and GNU stow
  become: true
  package: name={{ item }} state=present
  with_items:
    - git
    - stow
  when: not ansible_os_family == 'Darwin'

# Checks `git status --porcelain` to avoid overwritting uncommited changes
- name: Clone dotfile repo locally
  git:
    repo: "https://www.github.com/jeremy-hanna/dotfiles.git"
    dest: "{{ dotfile_dir }}"
    version: "master"
    accept_hostkey: false
  become: false

  #- name: Check if dotfiles are stow links to this directory already

- name: Link karabiner keybindings config
  file:
    src: "{{ dotfile_dir }}/.config/{{ item }}"
    dest: "~/.config/{{ item }}"
    state: link
  with_items:
    - karabiner
  when: ansible_os_family == 'Darwin'

- name: Link tmux config for use in iterm
  file:
    src: "{{ dotfile_dir }}/{{ item }}"
    dest: "~/{{ item }}"
    state: link
  with_items:
    - .tmux.conf
  when: ansible_os_family == 'Darwin'

- name: Link ctags config for use with vim
  file:
    src: "{{ dotfile_dir }}/{{ item }}"
    dest: "~/{{ item }}"
    state: link
  with_items:
    - .ctags
