# Clone the dotfiles, install stow, let subsequent roles link them
---
- name: Install git and GNU stow
  become: true
  package: name={{ item }} state=present
  with_items:
    - git
    - stow

# Checks `git status --porcelain` to avoid overwritting uncommited changes
- name: Clone dotfile repo locally
  git:
    repo: "https://www.github.com/jeremy-hanna/dotfiles.git"
    dest: "{{ dotfile_dir }}"
    version: "master"
    accept_hostkey: false
  become: false

  #- name: Check if dotfiles are stow links to this directory already
