# Install zsh, zplug, symlink .zshrc, zplug install, default shell
---
# ZSH is the default shell in Mac post-Catalina, no need to install
- name: Install ZSH
  become: true
  package: name={{ item }} state=present
  with_items:
    - zsh
  when: not ansible_os_family == 'Darwin'

- name: Install ZPlug if it doesn't exist
  git:
    repo: "https://github.com/zplug/zplug"
    dest: "~/.zplug"
    version: "master"
    accept_hostkey: false

- name: Link ZSH configs
  file:
    src: "{{ dotfile_dir }}/{{ item }}"
    dest: "~/{{ item }}"
    state: link
  with_items:
    - .zshrc

# ZSH is the default shell in Catalina
- name: Change default shell
  become: yes
  user: name={{ user }} shell=/usr/bin/zsh
  when: not ansible_os_family == 'Darwin'
