# Install zsh, zplug, symlink .zshrc, zplug install, default shell
---
- name: Install ZSH
  become: true
  package: name={{ item }} state=present
  with_items:
    - zsh

# Check if .zplug folder is exist.
- name: "Check if .zplug folder exist."
  stat:
    path: ~/.zplug
  register: zplug_folder

- name: Install ZPlug if it doesn't exist
  command: "git clone https://github.com/zplug/zplug ~/.zplug"
  when: zplug_folder.stat.exists == false

- name: Link ZSH configs
  file:
    src: "{{ dotfile_dir }}/{{ item }}"
    dest: "~/{{ item }}"
    state: link
  with_items:
    - .zshrc

- name: Change default shell
  become: yes
  user: name={{ user }} shell=/usr/bin/zsh
