# add config to X11/xorg.conf.d
---
# - name: Add trackpad configs to X11/xorg.conf.d
# become: true
# copy:
# content: |
# Section "InputClass"
# Identifier "touchpad"
# MatchIsTouchpad "on"
# Driver "libinput"
# Option "Tapping" "on"
# Option "ScrollMethod" "twofinger"
# Option "TappingButtonMap" "lrm"
# EndSection
# dest: /etc/X11/xorg.conf.d/90-touchpad.conf
