# Install caps2esc, compile it, link .Xmodmap
---
- name: Link Xmodmap configs
  file:
    src: "{{ dotfile_dir }}/{{ item }}"
    dest: "~/{{ item }}"
    state: link
  with_items:
    - .Xmodmap

- name: Install build packages
  become: true
  package: name={{ item }} state=present
  with_items:
    - cmake
    - libevdev-devel
    - systemd-devel
    - yaml-cpp-devel
    - boost-devel

- name: Clone interception tools repo locally
  git:
    repo: "https://gitlab.com/interception/linux/tools"
    dest: "{{ tools_dir }}/interception_tools"
    version: "master"
    accept_hostkey: false
  become: false

- name: CMake interception tools
  command: chdir={{ tools_dir }}/interception_tools cmake -B build -DCMAKE_BUILD_TYPE=Release

- name: Make install the interception tools
  command: chdir={{ tools_dir }}/interception_tools cmake --build build

- name: Make link the interception tools
  command: chdir={{ tools_dir }}/interception_tools/build make install
  become: true

- name: Clone caps2esc repo locally
  git:
    repo: "git@github.com:jeremy-hanna/caps2esc.git"
    dest: "{{ tools_dir }}/caps2esc"
    version: "master"
    accept_hostkey: false
  become: false

- name: CMake caps2esc
  command: chdir={{ tools_dir }}/caps2esc cmake -B build -DCMAKE_BUILD_TYPE=Release

- name: Make install the caps2esc
  command: chdir={{ tools_dir }}/caps2esc cmake --build build

- name: Add caps2esc configs /etc/udevmon.yaml
  copy:
    content: |
      - JOB: "intercept -g $DEVNODE | caps2esc | uinput -d $DEVNODE"
        DEVICE:
          EVENTS:
            EV_KEY: [KEY_CAPSLOCK, KEY_ESC]
    dest: /etc/udevmon.yaml
  become: true

# see: https://askubuntu.com/questions/979359/how-do-i-install-caps2esc/979606#979606
# FIXME: this should be improved, there is a lot of it not starting on system boot and failures in general - would also be nice to have a system warning when it is broken
- name: Add interception systemd config to /etc/systemd/system
  copy:
    content: |
      [Unit]
      Description=udevmon
      Wants=systemd-udev-settle.service
      After=systemd-udev-settle.service
      Before=plasma-workspace.target

      [Service]
      ExecStart=/usr/bin/nice -n -20 /usr/local/bin/udevmon -c /etc/udevmon.yaml
      Nice=-20
      Restart=on-failure
      OOMScoreAdjust=-1000

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/udevmon.service
  become: true

- name: Starting interception udevmon
  service:
    name: udevmon
    state: started
  become: true

  # - name: Uninstall build packages
  # become: true
  # package: name={{ item }} state=absent
  # with_items:
  # - cmake
  # - yaml-cpp-devel
  # - libevdev-devel
    # - libudev-devel
    # - gcc-c++
