# install urxvt-unicode-256color, link .Xdefaults, wget Monoid font
---
- name: Install rxvt
  become: true
  package: name={{ item }} state=present
  with_items:
    - rxvt-unicode

- name: Link Monoid font
  file:
    src: "{{ dotfile_dir }}/{{ item }}/"
    dest: "~/.local/share/{{ item }}"
    state: link
  with_items:
    - fonts

- name: Bust font cache
  shell: fc-cache -f -v

- name: Link .Xresources
  file:
    src: "{{ dotfile_dir }}/{{ item }}"
    dest: "~/{{ item }}"
    state: link
  with_items:
    - .Xresources
