# Install vim, link dotfiles, install plugin deps (ctag + go + js), vim-plug install
---
- name: Uninstall OS ctags
  become: true
  package: name=ctags state=absent
  when: not ansible_os_family == 'Darwin'

- name: Enable Fedora Copr for universal-ctags
  become: true
  command:
    cmd: "dnf copr enable -y thindil/universal-ctags"
    creates: /etc/yum.repos.d/_copr_thindil-universal_ctags.repo
  when: not ansible_os_family == 'Darwin'

- name: Install latest vim and ctags
  become: true
  package: name={{ item }} state=present
  with_items:
    - vim-enhanced
    - universal-ctags
  when: not ansible_os_family == 'Darwin'

- name: Link Vim configs
  file:
    src: "{{ dotfile_dir }}/{{ item }}"
    dest: "~/{{ item }}"
    state: link
  with_items:
    - .vim
    - .vimrc

# silent installation, see: https://github.com/junegunn/vim-plug/issues/730
- name: install plugins with vim-plug
  shell: vim +'PlugInstall --sync' +qall &> /dev/null < /dev/tty
